import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import {Provider} from "@/components/provider";
import {Toaster} from "@/components/ui/toaster";

const poppins = Poppins({
    variable: "--font-poppins",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
    subsets: ["latin-ext"],
});

export const metadata: Metadata = {
    title: "Partner Program",
    // description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={`${poppins.variable} antialiased`}>
        <Provider>{children}</Provider>
        <Toaster/>
        </body>
        </html>
    );
}
